# ============== Application configuration ==================== #
spring:
  application:
    name: otp-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource: # Database configuration #
    url: jdbc:mysql://localhost:3306/otp_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 38NG/db@tro38
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
