spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mondtekton/ng-stars-otp
          clone-on-start: true
          default-label: main
server:
  port: 9292
