# ============ EMAIL SERVICE CONFIGURATION =============
spring:
  application:
    name: email-service
  config:
    import: "optional:configserver:http://localhost:8088"

  mail:
    host: smtp.gmail.com
    port: 587
    username: katohdavid@gmail.com
    password: fxzyuynzfnfvqoqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
